let arr  = [
    {
        "linking_activity_id": 1,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Reinforcement",
        "quantity": 130,
        "uom_name": "MT",
        "max_percentage": 50,
        "cumulative_quantity": 100,
        "prog_id": 6370,
        "total_quantity": 200,
        "progress_created": "2023-02-16",
        "maximum_progress_date": "2023-02-12",
        "minimum_progress_date": "2023-02-10",
        "projectActivityOne": {
            "activity_head": "Column"
        },
        "relationsAll": [],
        "data_id": 4,
        "sr_no3": 4,
        "data_parent_id": 3,
        "actual_start_date": "2023-02-16",
        "actual_end_date": "2023-02-14",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "17",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": 2343,
        "actual_duration": 297,
        "actual_com_duration": 231
    },
    {
        "linking_activity_id": 10,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Shuttering",
        "quantity": 4,
        "uom_name": "SFT",
        "max_percentage": 30,
        "cumulative_quantity": 60,
        "prog_id": 6371,
        "total_quantity": 200,
        "progress_created": "2023-02-16",
        "maximum_progress_date": "2023-02-16",
        "minimum_progress_date": "2023-02-16",
        "projectActivityOne": {
            "activity_head": "Column"
        },
        "relationsAll": [],
        "data_id": 5,
        "sr_no3": 5,
        "data_parent_id": 3,
        "actual_start_date": "2023-02-16",
        "actual_end_date": "2023-02-18",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "1",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": 2541,
        "actual_duration": 99,
        "actual_com_duration": 33
    },
    {
        "linking_activity_id": 19,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Reinforcement",
        "quantity": 8,
        "uom_name": "MT",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "Slab"
        },
        "relationsAll": [],
        "data_id": 6,
        "sr_no3": 6,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "1",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 28,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Shuttering",
        "quantity": 91,
        "uom_name": "SFT",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "Slab"
        },
        "relationsAll": [],
        "data_id": 7,
        "sr_no3": 7,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "12",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 2486,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Brickwork (230)",
        "quantity": 400,
        "uom_name": "CUM",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "Masonary"
        },
        "relationsAll": [],
        "data_id": 8,
        "sr_no3": 8,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "53",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 2971,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Wall plasting",
        "quantity": 200,
        "uom_name": "Manhours",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "Plasting"
        },
        "relationsAll": [],
        "data_id": 9,
        "sr_no3": 9,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "27",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 2980,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "Block Cutting",
        "quantity": 200,
        "uom_name": "CUM",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "Block"
        },
        "relationsAll": [],
        "data_id": 10,
        "sr_no3": 10,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "27",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 3122,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "MUKESH",
        "quantity": 200,
        "uom_name": "CUM",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "MUKESH HEAD"
        },
        "relationsAll": [],
        "data_id": 11,
        "sr_no3": 11,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "27",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 3131,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "MUKESH",
        "quantity": null,
        "uom_name": "CUM",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "MUKESH HEAD"
        },
        "relationsAll": [],
        "data_id": 12,
        "sr_no3": 12,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "0",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 3377,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "LakeActivity",
        "quantity": 200,
        "uom_name": "CFT",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "LakeActivityHead"
        },
        "relationsAll": [],
        "data_id": 13,
        "sr_no3": 13,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "27",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    },
    {
        "linking_activity_id": 3939,
        "planned_start_date": "2022-12-20",
        "planned_end_date": "2023-02-10",
        "gantt_link": null,
        "productivity": null,
        "activity": "chacha",
        "quantity": null,
        "uom_name": "BAGS",
        "max_percentage": null,
        "cumulative_quantity": null,
        "prog_id": null,
        "total_quantity": null,
        "progress_created": null,
        "maximum_progress_date": null,
        "minimum_progress_date": null,
        "projectActivityOne": {
            "activity_head": "hello"
        },
        "relationsAll": [],
        "data_id": 14,
        "sr_no3": 14,
        "data_parent_id": 3,
        "actual_start_date": null,
        "actual_end_date": "Invalid date",
        "projected_start_date": "2022-12-06",
        "projected_end_date": "2022-12-06",
        "working_hrs": "0",
        "start_margin": 627,
        "duration": 1749,
        "actual_start_margin": -637791,
        "actual_duration": 640365,
        "actual_com_duration": 640365
    }
]

let aaaa  = [
    {
        actual_end_date : "Invalid date"
    },
    {
        actual_end_date : "2022-11-20"
    },
]
let ppp = new Date(Math.max(...aaaa.filter((val) => val.actual_end_date != null && val.actual_end_date != "Invalid date").map(element => { return new Date(element.actual_end_date) })));
let actMaxDate = aaaa.filter((val) => val.actual_end_date != null && val.actual_end_date != "Invalid date")
console.log("actMaaaaaaaa",actMaxDate);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);
console.log("actMaaaaaaaa",ppp);